// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseConfig, isConfigComplete } from '@/config/global-config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

function getSupabaseClient(): ReturnType<typeof createClient<Database>> {
  if (supabaseInstance) {
    return supabaseInstance;
  }

  if (!isConfigComplete()) {
    console.error('❌ Configuração Supabase incompleta');
    throw new Error('Configuração Supabase incompleta. Verifique as variáveis de ambiente.');
  }

  const config = getSupabaseConfig();
  
  supabaseInstance = createClient<Database>(config.url, config.anonKey, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  return supabaseInstance;
}

export const supabase = getSupabaseClient();