name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: production
      GITHUB_ACTIONS: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: development
      
    - name: Build with base path
      run: npm run build:gh-pages
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      continue-on-error: true
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
      continue-on-error: true
        
    - name: Verify build output (fallback for local testing)
      run: |
        echo "Build completed successfully!"
        ls -la dist/
        echo "index.html exists:" 
        test -f dist/index.html && echo "✓ Yes" || echo "✗ No"
        echo "Build artifacts summary:"
        find dist -type f -name "*.css" -o -name "*.js" | wc -l | xargs echo "Found files:"

  deploy:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.actor != 'nektos/act')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
